### ISSUE TITLE
Support Cray compiler

### ISSUE THREAD

**Issue by pletzer** [WatershedModels/SWAT#4]
Currently, SWAT's CMake build system support a set of compilers that does not include Cray. To support the Cray compiler the following changes need to be made:
(1) In the top CMakeLists.txt one needs to set the FLAG_L{72,80,132} variable. For Cray it is -N72, -N80 and -N132
(2) In cmake/SetFortranFlags.cmake one needs to the compiler optimization and switches

**Comment by crazyzlj** [comment]
This pull request has been approved and merged. Thank you very much!
