### ISSUE TITLE
Cray compiler error

### ISSUE THREAD

**Issue by pletzer** [WatershedModels/SWAT#6]
With the Cray compiler I get

mahuika01/nesi/nobackup/pletzera/swat/SWAT-pletzer/build_cray$ make
/scale_wlg_persistent/filesets/opt_nesi/CS400_centos7_bdw/CMake/3.22.1/bin/cmake -S/nesi/nobackup/pletzera/swat/SWAT-pletzer -B/nesi/nobackup/pletzera/swat/SWAT-pletzer/build_cray --check-build-system CMakeFiles/Makefile.cmake 0
/scale_wlg_persistent/filesets/opt_nesi/CS400_centos7_bdw/CMake/3.22.1/bin/cmake -E cmake_progress_start /nesi/nobackup/pletzera/swat/SWAT-pletzer/build_cray/CMakeFiles /nesi/nobackup/pletzera/swat/SWAT-pletzer/build_cray//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/scale_wlg_nobackup/filesets/nobackup/pletzera/swat/SWAT-pletzer/build_cray'
make  -f src/CMakeFiles/swat.dir/build.make src/CMakeFiles/swat.dir/depend
make[2]: Entering directory `/scale_wlg_nobackup/filesets/nobackup/pletzera/swat/SWAT-pletzer/build_cray'
[  0%] Generating biofilm.o
cd /nesi/nobackup/pletzera/swat/SWAT-pletzer/build_cray/src && /opt/cray/pe/craype/2.5.16/bin/ftn -O0 -h error_on_warning -G0 -h bounds -N80 -c /nesi/nobackup/pletzera/swat/SWAT-pletzer/src/biofilm.f

ftn-1698 crayftn: ERROR BIOFILM, File = ../../../scale_wlg_nobackup/filesets/nobackup/pletzera/swat/SWAT-pletzer/src/biofilm.f, Line = 188, Column = 33
  Type REAL(kind=4) is not allowed for the "A1" argument of intrinsic DMAX1.

**Comment by crazyzlj** [comment]
Pull request merged!
